"""inital mirtaions

Revision ID: ef581bcb9460
Revises: 
Create Date: 2020-08-05 01:02:02.400739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef581bcb9460'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('apellidop', sa.String(length=80), nullable=False),
    sa.Column('apellidom', sa.String(length=80), nullable=False),
    sa.Column('edad', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=80), nullable=False),
    sa.Column('calle', sa.String(length=80), nullable=False),
    sa.Column('colonia', sa.String(length=80), nullable=False),
    sa.Column('numdire', sa.String(length=70), nullable=False),
    sa.Column('image_1', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('apellidop', sa.String(length=80), nullable=False),
    sa.Column('apellidom', sa.String(length=80), nullable=False),
    sa.Column('edad', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=80), nullable=False),
    sa.Column('calle', sa.String(length=80), nullable=False),
    sa.Column('colonia', sa.String(length=80), nullable=False),
    sa.Column('numdire', sa.String(length=70), nullable=False),
    sa.Column('image_1', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dueño',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('apellidop', sa.String(length=80), nullable=False),
    sa.Column('apellidom', sa.String(length=80), nullable=False),
    sa.Column('edad', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=80), nullable=False),
    sa.Column('calle', sa.String(length=80), nullable=False),
    sa.Column('colonia', sa.String(length=80), nullable=False),
    sa.Column('numdire', sa.String(length=70), nullable=False),
    sa.Column('image_1', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('f_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('zipcode', sa.String(length=50), nullable=True),
    sa.Column('profile', sa.String(length=200), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('profile', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('apellidop', sa.String(length=80), nullable=False),
    sa.Column('apellidom', sa.String(length=80), nullable=False),
    sa.Column('edad', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=80), nullable=False),
    sa.Column('calle', sa.String(length=80), nullable=False),
    sa.Column('colonia', sa.String(length=80), nullable=False),
    sa.Column('numdire', sa.String(length=70), nullable=False),
    sa.Column('image_1', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('colors', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('image_1', sa.String(length=150), nullable=False),
    sa.Column('image_2', sa.String(length=150), nullable=False),
    sa.Column('image_3', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.String(length=80), nullable=False),
    sa.Column('total', sa.String(length=80), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('addproduct_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addproduct_id'], ['addproduct.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta')
    op.drop_table('addproduct')
    op.drop_table('vendedor')
    op.drop_table('user')
    op.drop_table('register')
    op.drop_table('dueño')
    op.drop_table('cliente')
    op.drop_table('category')
    op.drop_table('brand')
    op.drop_table('administrador')
    # ### end Alembic commands ###
